// Auto-generated offline & standalone registration roster bundle
window.QAURA_PRELOADED_REGISTRATIONS = [
  {
    "id": 49,
    "regId": "QAURA-2026-5241",
    "firstName": "Bala soundarya",
    "lastName": "A V",
    "mobile": "9363599407",
    "email": "balasoundaryaav@gmail.com",
    "college": "NPR college of engineering and technology",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Tech sparks",
    "leaderName": "Bala soundarya A V",
    "leaderPhone": "9363599407",
    "leaderEmail": "balasoundaryaav@gmail.com",
    "tm2": "Keerthana J",
    "tm3": "No",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.953Z",
    "verifiedAt": null
  },
  {
    "id": 51,
    "regId": "QAURA-2026-4808",
    "firstName": "Kishore",
    "lastName": "R",
    "mobile": "7358500253",
    "email": "kishore.r7353@gmail.com",
    "college": "Sree sakthi engineering College",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "TECH ZYREX",
    "leaderName": "Kishore.R",
    "leaderPhone": "7358500253",
    "leaderEmail": "kishore.r7353@gmail.com",
    "tm2": "Habeeb Raja.S",
    "tm3": "Mathan raj.S",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.955Z",
    "verifiedAt": null
  },
  {
    "id": 55,
    "regId": "QAURA-2026-5497",
    "firstName": "MANIKANDAN",
    "lastName": "S",
    "mobile": "9965559912",
    "email": "manikandanwar975@gmail.com",
    "college": "SREE SAKTHI ENGINEERING COLLEGE",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "TECH INFINIX",
    "leaderName": "MANIKANDAN. S",
    "leaderPhone": "9965559912",
    "leaderEmail": "manikandanwar975@gmail.com",
    "tm2": "Jahir hussain. S",
    "tm3": "Kalaiarsan. S",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.958Z",
    "verifiedAt": null
  },
  {
    "id": 54,
    "regId": "QAURA-2026-8020",
    "firstName": "R. Kishore",
    "lastName": "Kumar",
    "mobile": "9597797965",
    "email": "kishorekumarr601@gmail.com",
    "college": "Sree sakthi engineering college",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Tech Nova",
    "leaderName": "R. Kishore Kumar",
    "leaderPhone": "9597797965",
    "leaderEmail": "kishorekumarr601@gmail.com",
    "tm2": "K. Jeeva",
    "tm3": "M. Abishek",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.957Z",
    "verifiedAt": null
  },
  {
    "id": 53,
    "regId": "QAURA-2026-9255",
    "firstName": "Anbu",
    "lastName": "Dhanush",
    "mobile": "9342596848",
    "email": "abishek76217621@gmail.com",
    "college": "Sree Sakthi Engineering college Coimbatore (Technical campus)",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "TeamTechnitix",
    "leaderName": "Dhanush",
    "leaderPhone": "9360754243",
    "leaderEmail": "dhanushjaya68@gmail.com",
    "tm2": "Abishek T",
    "tm3": "Anbu P",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.956Z",
    "verifiedAt": null
  },
  {
    "id": 52,
    "regId": "QAURA-2026-3619",
    "firstName": "Dharani",
    "lastName": "D",
    "mobile": "9025704849",
    "email": "dharanidakshinamoorthy07@gmail.com",
    "college": "Jaishriram engineering college",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Geoslot",
    "leaderName": "Dharani D",
    "leaderPhone": "9025704849",
    "leaderEmail": "dharanidakshinamoorthy07@gmail.com",
    "tm2": "Malarvizhi M",
    "tm3": "Manisha M",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.956Z",
    "verifiedAt": null
  },
  {
    "id": 50,
    "regId": "QAURA-2026-6040",
    "firstName": "Niranjana",
    "lastName": "S",
    "mobile": "8072714275",
    "email": "niranjanaseenivasagan15@gmail.com",
    "college": "NPR College of Engineering and Technology",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Innovatrix",
    "leaderName": "Niranjana S",
    "leaderPhone": "8072714275",
    "leaderEmail": "niranjanaseenivasagan15@gmail.com",
    "tm2": "Abinaya S",
    "tm3": "Abi rubha M",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.954Z",
    "verifiedAt": null
  },
  {
    "id": 48,
    "regId": "QAURA-2026-3192",
    "firstName": "Kalaivani",
    "lastName": "B",
    "mobile": "8015812583",
    "email": "kalaivanib2111@gmail.com",
    "college": "Dhanalakshmi Srinivasan college of engineering",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Hackzen",
    "leaderName": "Kalaivani B",
    "leaderPhone": "8015812583",
    "leaderEmail": "kalaivanib2111@gmail.com",
    "tm2": "Jayasri V",
    "tm3": "Kaviya T",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.953Z",
    "verifiedAt": null
  },
  {
    "id": 47,
    "regId": "QAURA-2026-6557",
    "firstName": "Aysha",
    "lastName": "Shifana M",
    "mobile": "7358868804",
    "email": "ayshashifana370@gmail.com",
    "college": "NPR college of engineering and technology",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Tech titans",
    "leaderName": "Aysha shifana m",
    "leaderPhone": "7358868504",
    "leaderEmail": "ayshashifana370@gmail.com",
    "tm2": "Asin Fathima F",
    "tm3": "Afritha safrin s",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.952Z",
    "verifiedAt": null
  },
  {
    "id": 46,
    "regId": "QAURA-2026-2922",
    "firstName": "Gokul",
    "lastName": "M",
    "mobile": "7092701082",
    "email": "gokulm583225205020@nprcolleges.org",
    "college": "N.P.R college of engineering and technology",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Spartens",
    "leaderName": "Gokul M",
    "leaderPhone": "7092701082",
    "leaderEmail": "gokulm583225205020@nprcolleges.org",
    "tm2": "Vasanth P",
    "tm3": "Ganesh K",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.951Z",
    "verifiedAt": null
  },
  {
    "id": 45,
    "regId": "QAURA-2026-4137",
    "firstName": "Santhosh",
    "lastName": "A",
    "mobile": "9342746200",
    "email": "santhoshanand7628@gmail.com",
    "college": "Npr college of engineering and technology",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Tech nova",
    "leaderName": "Santhosh A",
    "leaderPhone": "9342746200",
    "leaderEmail": "santhoshanand7628@gmail.com",
    "tm2": "Fazil Ahamed I",
    "tm3": "Harish kannan A",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.950Z",
    "verifiedAt": null
  },
  {
    "id": 44,
    "regId": "QAURA-2026-1038",
    "firstName": "Kavitha",
    "lastName": "Saraswathi S",
    "mobile": "9791581064",
    "email": "kavitha24197@gmail.com",
    "college": "Dhanalakshmi Srinivasan College of Engineering",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "TechWanderers",
    "leaderName": "Kavitha Saraswathi S",
    "leaderPhone": "9791581064",
    "leaderEmail": "kavitha24197@gmail.com",
    "tm2": "Kaviya S",
    "tm3": "Jayasri R",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.948Z",
    "verifiedAt": null
  },
  {
    "id": 43,
    "regId": "QAURA-2026-7687",
    "firstName": "Vishwa",
    "lastName": "R",
    "mobile": "8248069652",
    "email": "rvishwa961@gmail.com",
    "college": "NPR college of engineering and technology",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "CodeStorm",
    "leaderName": "Vishwa R",
    "leaderPhone": "8248069652",
    "leaderEmail": "rvishwa961@gmail.com",
    "tm2": "Aswin Raja S",
    "tm3": "Dhanajeyam S",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.947Z",
    "verifiedAt": null
  },
  {
    "id": 42,
    "regId": "QAURA-2026-8258",
    "firstName": "Mohamed",
    "lastName": "Binnathik M",
    "mobile": "9884802131",
    "email": "717825p132@kce.ac.in",
    "college": "Karpagam College of Engineering",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Tech Titans",
    "leaderName": "Mohamed Binnathik M",
    "leaderPhone": "9884802131",
    "leaderEmail": "717825p132@kce.ac.in",
    "tm2": "Vikram N",
    "tm3": "Thanush Sakthi V S",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.946Z",
    "verifiedAt": null
  },
  {
    "id": 41,
    "regId": "QAURA-2026-3244",
    "firstName": "Shai Shmithesh",
    "lastName": "M R",
    "mobile": "9025358960",
    "email": "26adl11@kpriet.ac.in",
    "college": "KPR Institute of Engineering and Technology",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Triple Threat",
    "leaderName": "Shai Shmithesh M R",
    "leaderPhone": "9025358960",
    "leaderEmail": "26adl11@kpriet.ac.in",
    "tm2": "Anbarasu S",
    "tm3": "Karthick S",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.944Z",
    "verifiedAt": null
  },
  {
    "id": 40,
    "regId": "QAURA-2026-9051",
    "firstName": "AGSAYA VIISNU",
    "lastName": "P B",
    "mobile": "7397330888",
    "email": "agsayaviisnu77@gmail.com",
    "college": "PSG COLLEGE OF ART'S & SCIENCE",
    "techEvent": "Cloud Craft (Workshop)",
    "nonTechEvent": "None",
    "fee": "₹250",
    "teamName": "",
    "leaderName": "",
    "leaderPhone": "",
    "leaderEmail": "",
    "tm2": "",
    "tm3": "",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.943Z",
    "verifiedAt": null
  },
  {
    "id": 39,
    "regId": "QAURA-2026-2716",
    "firstName": "Dhaarshan",
    "lastName": "V",
    "mobile": "8525813344",
    "email": "26csl08@kpriet.ac.in",
    "college": "KPR Institute of Engineering and Technology",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Alt+F4",
    "leaderName": "Dhaarshan",
    "leaderPhone": "8525813344",
    "leaderEmail": "26csl08@kpriet.ac.in",
    "tm2": "Ilakkya",
    "tm3": "Mownitha",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.942Z",
    "verifiedAt": null
  },
  {
    "id": 38,
    "regId": "QAURA-2026-8563",
    "firstName": "Sharvin",
    "lastName": "SJ",
    "mobile": "7598419666",
    "email": "sharvin@sharvinsj.com",
    "college": "Sri Chaitanaya",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Brainstormers",
    "leaderName": "Sharvin SJ",
    "leaderPhone": "7598419666",
    "leaderEmail": "sharvin@sharvinsj.com",
    "tm2": "Shanmitha S",
    "tm3": "Gowdham Rangarajan",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.941Z",
    "verifiedAt": null
  },
  {
    "id": 37,
    "regId": "QAURA-2026-7594",
    "firstName": "SHASHISHEKHAR",
    "lastName": "CHAUBEY",
    "mobile": "9488352388",
    "email": "26u1020488507@srcas.ac.in",
    "college": "Sri Ramakrishna College of Arts and Science",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Nexora",
    "leaderName": "Shashi Shekhar Chaubey",
    "leaderPhone": "9488352388",
    "leaderEmail": "26u1020488507@srcas.ac.in",
    "tm2": "A Reshma",
    "tm3": "Aafhiya S",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.940Z",
    "verifiedAt": null
  },
  {
    "id": 36,
    "regId": "QAURA-2026-3082",
    "firstName": "Pranav",
    "lastName": "S",
    "mobile": "9488025121",
    "email": "pranavsiva22@gmail.com",
    "college": "Rathinam Technical Campus",
    "techEvent": "Hackathon",
    "nonTechEvent": "None",
    "fee": "₹300 (Team)",
    "teamName": "Elite Tig3rs",
    "leaderName": "Arun kumar M",
    "leaderPhone": "7708059324",
    "leaderEmail": "Offensivehunt3r@gmail.com",
    "tm2": "Pranav S",
    "tm3": "Kayal Vizee S",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.939Z",
    "verifiedAt": null
  },
  {
    "id": 34,
    "regId": "QAURA-2026-1701",
    "firstName": "Mohammed",
    "lastName": "S",
    "mobile": "7558142808",
    "email": "md.thabrez283@gmail.com",
    "college": "Rathinam Global deemed to be university",
    "techEvent": "Cyber Forge (Workshop)",
    "nonTechEvent": "Prompt Generating",
    "fee": "₹250",
    "teamName": "",
    "leaderName": "",
    "leaderPhone": "",
    "leaderEmail": "",
    "tm2": "",
    "tm3": "",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.937Z",
    "verifiedAt": null
  },
  {
    "id": 33,
    "regId": "QAURA-2026-8161",
    "firstName": "Sunil",
    "lastName": "kumar",
    "mobile": "6385865347",
    "email": "sunilaathi866@gmail.com",
    "college": "RGU",
    "techEvent": "Cyber Forge (Workshop)",
    "nonTechEvent": "None",
    "fee": "₹250",
    "teamName": "",
    "leaderName": "",
    "leaderPhone": "",
    "leaderEmail": "",
    "tm2": "",
    "tm3": "",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.936Z",
    "verifiedAt": null
  },
  {
    "id": 30,
    "regId": "QAURA-2026-4081",
    "firstName": "Bala",
    "lastName": "Suriya",
    "mobile": "9384160788",
    "email": "bala@gmail.com",
    "college": "Rathinam global University",
    "techEvent": "Hackathon",
    "nonTechEvent": "Prompt Generating",
    "fee": "₹300 (Team)",
    "teamName": "Cyber strike",
    "leaderName": "Bala",
    "leaderPhone": "9363234993",
    "leaderEmail": "bala@gmail.com",
    "tm2": "Sridev",
    "tm3": "Vishal",
    "tm4": "",
    "paymentScreenshot": "",
    "status": "Pending Verification",
    "isActive": true,
    "createdAt": "2026-10-07T14:46:44.932Z",
    "verifiedAt": null
  }
];
